version: 2.1
workflows:
  test:
    jobs:
      - test

orbs:
  python: circleci/python@0.2.1

jobs:
  test:
    executor: python/default

    steps:
      - checkout

      - run:
          name: Install test dependencies
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install flake8 isort pre-commit pytest pytest-cov

      - run:
          name: Linters
          command: |
            . venv/bin/activate
            pre-commit run -a
